import React, { useState } from 'react';
import { useData } from '../context/DataContext';
import { generateExecutiveReport } from '../services/geminiService';
import { FileText, Loader2, Sparkles, Printer, Download } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

export const Reports: React.FC = () => {
    const { activities, budget, beneficiaries, compliance } = useData();
    const [report, setReport] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);

    const handleGenerate = async () => {
        setLoading(true);
        const text = await generateExecutiveReport(activities, budget, beneficiaries, compliance);
        setReport(text);
        setLoading(false);
    };

    return (
        <div className="space-y-6 max-w-4xl mx-auto">
             <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                <div>
                    <h1 className="text-2xl font-bold text-slate-900">Reporting Hub</h1>
                    <p className="text-slate-500 text-sm">Automated donor reporting for CFLI.</p>
                </div>
            </div>

            <div className="bg-gradient-to-r from-blue-600 to-indigo-700 rounded-2xl p-8 text-white shadow-lg">
                <div className="flex items-center gap-3 mb-4">
                    <Sparkles className="w-6 h-6 text-yellow-300" />
                    <h2 className="text-xl font-bold">AI-Powered Executive Summary</h2>
                </div>
                <p className="text-blue-100 mb-6 max-w-xl">
                    Generate a professional narrative report summarizing project progress, financial status, and beneficiary impact using real-time data from the platform.
                </p>
                <button 
                    onClick={handleGenerate} 
                    disabled={loading}
                    className="bg-white text-blue-700 hover:bg-blue-50 px-6 py-3 rounded-lg font-semibold flex items-center gap-2 transition disabled:opacity-50 shadow-sm"
                >
                    {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : <Sparkles className="w-5 h-5" />}
                    {loading ? 'Analyzing Data...' : 'Generate Report with AI'}
                </button>
            </div>

            {report && (
                <div className="bg-white rounded-xl border border-slate-200 shadow-sm animate-fade-in p-8 print:p-0 print:border-none print:shadow-none">
                    <div className="flex justify-between items-start mb-8 border-b border-slate-100 pb-4 no-print">
                        <div>
                            <h3 className="text-lg font-bold text-slate-800">Generated Report Draft</h3>
                            <p className="text-sm text-slate-500">Review and edit before export.</p>
                        </div>
                        <div className="flex gap-2">
                             <button onClick={() => window.print()} className="p-2 hover:bg-slate-100 rounded text-slate-600">
                                <Printer className="w-5 h-5" />
                            </button>
                            <button className="p-2 hover:bg-slate-100 rounded text-slate-600">
                                <Download className="w-5 h-5" />
                            </button>
                        </div>
                    </div>
                    
                    <div className="prose prose-slate max-w-none">
                        <div className="mb-6">
                            <h1 className="text-2xl font-bold text-slate-900 mb-2">Monthly Progress Report</h1>
                            <p className="text-slate-600">Project: CFLI-2025-MPUTO-MZ-0001</p>
                            <p className="text-slate-600">Date: {new Date().toLocaleDateString()}</p>
                        </div>
                        <ReactMarkdown>{report}</ReactMarkdown>
                    </div>

                    <div className="mt-8 pt-6 border-t border-slate-200 text-center text-xs text-slate-400 no-print">
                        Generated by Gemini 3 Flash Preview • Verify data against source documents before submission.
                    </div>
                </div>
            )}
        </div>
    );
};